model_name: baseline_gru_det
model_type: baseline_gru
probabilistic: false
train_config:
  epochs: 60
  seed: 42
  horizon: 28
  seq_len: 28
  autoregressive: true
  use_normalise: false
  feature_set: sales_hierarchy_dow
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
  optimiser: adamw
  optimiser_params: &id001
    lr: 0.004157774327737044
    weight_decay: 1.0616834286838543e-07
  scheduler: plateau
  scheduler_params: &id002
    patience: 5
    factor: 0.5
  clip_grad_norm: 0.7332192497176724
  hidden: 109.35864817594955
  layers: 1.6981393949882269
  dropout: 0.10207515495539755
  n_features: 6
  vocab_sizes: &id003
    state_id_int: 3
    store_id_int: 5
    cat_id_int: 3
    dept_id_int: 4
best_config:
  epochs: 60
  seed: 42
  horizon: 28
  seq_len: 28
  autoregressive: true
  use_normalise: false
  feature_set: sales_hierarchy_dow
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
  optimiser: adamw
  optimiser_params: *id001
  scheduler: plateau
  scheduler_params: *id002
  clip_grad_norm: 0.7332192497176724
  hidden: 109.35864817594955
  layers: 1.6981393949882269
  dropout: 0.10207515495539755
  n_features: 6
  vocab_sizes: *id003
search_space:
  optimiser_params.lr:
  - 0.0001
  - 0.01
  - log
  optimiser_params.weight_decay:
  - 1.0e-07
  - 0.001
  - log
  hidden:
  - 32
  - 128
  - uniform
  layers:
  - 1
  - 2
  - uniform
  dropout:
  - 0.0
  - 0.3
  - uniform
  clip_grad_norm:
  - 0.5
  - 2.0
  - uniform
