model_name: hierarchical_gru_det
model_type: hierarchical_gru
probabilistic: false
train_config:
  epochs: 60
  seed: 42
  horizon: 28
  seq_len: 28
  autoregressive: true
  use_normalise: false
  feature_set: sales_hierarchy_dow
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
  optimiser: adamw
  optimiser_params: &id001
    lr: 0.0001435005520975851
    weight_decay: 0.00041848515040279207
  scheduler: plateau
  scheduler_params: &id002
    patience: 5
    factor: 0.5
  clip_grad_norm: 0.5177960092130482
  hidden: 229.04999684871933
  layers: 1.1417146997773069
  dropout: 0.1095011585922488
  embed_dim: 9.351822226370246
  n_features: 6
  vocab_sizes: &id003
    state_id_int: 3
    store_id_int: 5
    cat_id_int: 3
    dept_id_int: 4
best_config:
  epochs: 60
  seed: 42
  horizon: 28
  seq_len: 28
  autoregressive: true
  use_normalise: false
  feature_set: sales_hierarchy_dow
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
  optimiser: adamw
  optimiser_params: *id001
  scheduler: plateau
  scheduler_params: *id002
  clip_grad_norm: 0.5177960092130482
  hidden: 229.04999684871933
  layers: 1.1417146997773069
  dropout: 0.1095011585922488
  embed_dim: 9.351822226370246
  n_features: 6
  vocab_sizes: *id003
search_space:
  optimiser_params.lr:
  - 5.0e-05
  - 0.005
  - log
  optimiser_params.weight_decay:
  - 1.0e-07
  - 0.001
  - log
  hidden:
  - 64
  - 256
  - uniform
  layers:
  - 1
  - 3
  - uniform
  dropout:
  - 0.05
  - 0.3
  - uniform
  embed_dim:
  - 4
  - 12
  - uniform
  clip_grad_norm:
  - 0.25
  - 1.5
  - uniform
