model_name: baseline_gru_prob
model_type: baseline_gru
probabilistic: true
train_config:
  epochs: 60
  seed: 42
  horizon: 28
  seq_len: 28
  autoregressive: false
  use_normalise: false
  feature_set: sales_hierarchy_dow
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
  optimiser: adamw
  optimiser_params: &id001
    lr: 0.004764493135935548
    weight_decay: 3.630772517056739e-05
  scheduler: plateau
  scheduler_params: &id002
    patience: 5
    factor: 0.5
  clip_grad_norm: 1.2199998894328061
  hidden: 85.46717540236604
  layers: 1.6846142509898745
  dropout: 0.25285557605694287
  sigma_reg: 0.00041513932589846893
  n_features: 6
best_config:
  epochs: 60
  seed: 42
  horizon: 28
  seq_len: 28
  autoregressive: false
  use_normalise: false
  feature_set: sales_hierarchy_dow
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
  optimiser: adamw
  optimiser_params: *id001
  scheduler: plateau
  scheduler_params: *id002
  clip_grad_norm: 1.2199998894328061
  hidden: 85.46717540236604
  layers: 1.6846142509898745
  dropout: 0.25285557605694287
  sigma_reg: 0.00041513932589846893
  n_features: 6
search_space:
  optimiser_params.lr:
  - 5.0e-05
  - 0.005
  - log
  optimiser_params.weight_decay:
  - 1.0e-07
  - 0.001
  - log
  hidden:
  - 32
  - 128
  - uniform
  layers:
  - 1
  - 2
  - uniform
  dropout:
  - 0.0
  - 0.3
  - uniform
  clip_grad_norm:
  - 0.25
  - 1.5
  - uniform
  sigma_reg:
  - 0.0001
  - 0.05
  - log
