model_name: baseline_gru_det
model_type: baseline_gru
probabilistic: false
train_config:
  epochs: 60
  seed: 42
  horizon: 28
  seq_len: 28
  autoregressive: true
  use_normalise: false
  feature_set: sales_hierarchy_dow
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
  optimiser: adamw
  optimiser_params: &id001
    lr: 0.0019004375238737116
    weight_decay: 1.2590501261927495e-07
  scheduler: plateau
  scheduler_params: &id002
    patience: 5
    factor: 0.5
  clip_grad_norm: 1.515049231134367
  hidden: 58.40281456343545
  layers: 1.2232107381488229
  dropout: 0.22094136424920371
  n_features: 6
best_config:
  epochs: 60
  seed: 42
  horizon: 28
  seq_len: 28
  autoregressive: true
  use_normalise: false
  feature_set: sales_hierarchy_dow
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
  optimiser: adamw
  optimiser_params: *id001
  scheduler: plateau
  scheduler_params: *id002
  clip_grad_norm: 1.515049231134367
  hidden: 58.40281456343545
  layers: 1.2232107381488229
  dropout: 0.22094136424920371
  n_features: 6
search_space:
  optimiser_params.lr:
  - 0.0001
  - 0.01
  - log
  optimiser_params.weight_decay:
  - 1.0e-07
  - 0.001
  - log
  hidden:
  - 32
  - 128
  - uniform
  layers:
  - 1
  - 2
  - uniform
  dropout:
  - 0.0
  - 0.3
  - uniform
  clip_grad_norm:
  - 0.5
  - 2.0
  - uniform
